In [10]:
import numpy as np

In [7]:
from sklearn.model_selection import train_test_split

In [13]:
x=np.arange(10).reshape(5,2)
y=range(5)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
list(y)

[0, 1, 2, 3, 4]

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [20]:
x_train

array([[8, 9],
       [6, 7],
       [0, 1]])

In [21]:
y_train

[4, 3, 0]

In [22]:
x_test

array([[2, 3],
       [4, 5]])

In [23]:
y_test

[1, 2]